name: Prometheus checks

on:
  workflow_dispatch:
  push:
    paths:
      - "prometheus/**"

jobs:
  promtool:
    name: Checks via promtool

    runs-on: ubuntu-22.04

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install prometheus
        run: |
          wget https://github.com/prometheus/prometheus/releases/download/v2.47.1/prometheus-2.47.1.linux-amd64.tar.gz
          tar -xf prometheus-2.47.1.linux-amd64.tar.gz

      - name: Run configuration check
        run: ./prometheus-2.47.1.linux-amd64/promtool check config prometheus/prometheus.yml

      - name: Run rules check
        run: promtool check rules prometheus/*.rule
        if: ${{ always() }}

      - name: Run rules tests
        run: promtool test rules prometheus/*.test
        if: ${{ always() }}
